name: app_helper_generator
description: Awesome code generator
version: 1.0.4

homepage: https://github.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  build: ^2.3.1
  meta: ^1.8.0
  source_gen: ^1.2.6
  app_helper: ^1.0.4
dev_dependencies:
  build_runner: ^2.3.0
  build_test: ^2.1.5
  test: ^1.15.3