name: app_helper_generator
description: Awesome code generator
version: 1.0.2

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  analyzer: ^2.0.0
  build: ^2.0.3
  meta: ^1.7.0
  source_gen: ^1.0.3
  app_helper: ^1.0.2
dev_dependencies:
  build_runner: ^2.0.6
  build_test: ^2.1.2
  test: ^1.15.3