name: app_helper_generator
description: Awesome code generator
version: 1.0.0
authors:
  - Narek Hakobyan <narek.hakobyan.07@gmail.com>

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  analyzer: ">=0.40.0 <2.0.0"
  build: ^1.3.0
  meta: ^1.3.0
  source_gen: ^0.9.10+3
  app_helper: 1.0.0
dev_dependencies:
  build_runner: ^1.10.2
  build_test: ^1.2.1
  test_coverage: ^0.4.3
  test: ^1.15.3