name: app_helper_generator
description: Awesome code generator
version: 1.0.0
authors:
  - Narek Hakobyan <narek.hakobyan.07@gmail.com>

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  analyzer: ^1.1.0
  build: ^2.0.0
  meta: ^1.3.0
  source_gen: ^1.0.0
  app_helper:
    path: ../app_helper
dev_dependencies:
  build_runner: ^1.11.5
  build_test: ^1.3.7
  test: ^1.15.3