name: app_helper_generator
description: Awesome code generator
version: 1.0.3

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  analyzer: ^3.0.0
  build: ^2.2.1
  meta: ^1.7.0
  source_gen: ^1.2.1
  app_helper: ^1.0.2
dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  test: ^1.15.3