name: app_helper_generator
description: Awesome code generator
version: 0.0.1
authors:
  - Narek Hakobyan <narek.hakobyan.07@gmail.com>

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.11
  build: ^1.3.0
  meta: ^1.2.2
  source_gen: ^0.9.6
  app_helper:
    path: ../app_helper
dev_dependencies:
  build_runner: ^1.10.2
  build_test: ^1.2.1
  test_coverage: ^0.4.3
  test: ^1.15.3