name: app_helper
description: Awesome code generator
version: 0.0.2

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.7.0 <3.0.0"
dev_dependencies:
  test_coverage: ^0.4.3
  test: ^1.15.3
