name: app_helper
description: Awesome code generator
version: 1.0.3

homepage: https://gitlab.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dev_dependencies:
  test_coverage: ^0.5.0
  test: ^1.15.3
