name: app_helper
description: Awesome code generator
version: 1.0.4

homepage: https://github.com/NarHakobyan/app-generator-library

environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  test: ^1.30.0
